actor_tau: 0.005
agent_conf: 2x3
agent_obsk: null
alpha: 0.05
alpha_lr: 0.0003
auto_alpha: true
batch_size: 256
beta_lr: 0.0001
beta_optimizer: adam
critic_lr: 0.0003
critic_lr_decay: false
critic_tau: 0.005
delta_base: 0.001
episode_limit: 1000
epoch_length: 1000
eval_n_episodes: 1
gamma: 0.99
huber_delta: 10.0
max_buffer_size: 1000000
max_grad_norm: 5.0
min_buffer_size: 1000
n_epochs: 4000
n_node: 256
n_train_repeat: 1
pi_lr: 0.0003
pi_lr_decay: false
r_scale: 1.0
save_interval: 100
scenario: Walker2d-v2
seed: null
squash: true
target_update_interval: 1
trpo: true
two_qf: true
update_interval: 1
