actor_tau: 0.005
agent_conf: 9|8
agent_obsk: null
alpha: 0.1
alpha_lr: 0.0003
auto_alpha: false
batch_size: 256
beta_lr: 0.0003
beta_optimizer: adam
critic_lr: 0.0003
critic_tau: 0.005
delta_base: 0.01
epoch_length: 1000
eval_n_episodes: 1
gamma: 0.99
huber_delta: 10.0
log_interval: 1
max_buffer_size: 1000000
max_grad_norm: 5.0
max_path_length: 1000
min_buffer_size: 1000
n_epochs: 10000
n_node: 256
n_train_repeat: 1
pi_lr: 0.0003
save_interval: 100
scenario: Humanoid-v2
seed: null
squash: true
target_update_interval: 1
trpo: true
two_qf: true
update_interval: 1
use_huber_loss: true
